#pragma once
#include <netinet/in.h> 
#include <sys/types.h>
#include <sys/socket.h>
#include <stdexcept>
#include <cstdlib> 
#include <arpa/inet.h> 
#include <netinet/in.h> 
#include <string.h>
#include <charconv>
#include <atomic>
#include <memory>
#include <pthread.h>
#include <sched.h>
#include <algorithm>
#include <sched.h>
#include <fcntl.h>
#include <unistd.h>
#include <iostream>

// create concept: T needs to have a generator function!
// T doesn't actually need a constructor? Kinda does need a destructor though!
// arrays will be auto delete[] when go out of scope bs unique_ptr
// concept is that only primitives so no destructor so it is safe when we legit just do the storage trick
// if we had allocated data, when we allocator.deallocate, the delete[] will not get called to free allocated storage pointed to by T objects


template<class T>
concept triviallyDestructable = std::is_trivially_destructible_v<T> == true;

template <class Generator, class Generated>
concept isGenerator = requires(Generated a, Generator gen){
    {gen.generate(a)} -> std::same_as<void>;
};

template<triviallyDestructable T>
class exchangeSimulator {
    public:
        exchangeSimulator(int, int);


        template<class G>
        //requires isGenerator<G, T>
        void run(std::atomic<bool>&, const struct sockaddr_in*, G& generator, int numSim);

        ~exchangeSimulator(){
            allocator.deallocate(sendBuffer, batchSize);
        }

        int getCounter(){return counter;}
        void clearCounter(){counter = 0;}

        // rule of 5 because we broke RAII and needed a destructor(unique_ptr default initializes objects and we dont want to default construct!)
        exchangeSimulator(const exchangeSimulator&) = delete;
        exchangeSimulator(exchangeSimulator&&) = delete;
        exchangeSimulator& operator=(exchangeSimulator&&) = delete;
        exchangeSimulator& operator=(const exchangeSimulator&) = delete;

    private:
        int sockfd;
        int port;
        int batchSize;
        int counter{};
        struct sockaddr_in addr;
        std::allocator<T> allocator; // define allocator before so member initializer list goes in the right order!
        std::unique_ptr<struct mmsghdr[]> msgs; // we use unique_ptr to C-style instead of vectors because vectors don't let us get non-const refs to their elements
        std::unique_ptr<struct iovec[]> iovecs; // heap allocating all of this because batch size could be up to 1024 and these structs are >4 bytes so not lovely on stack T could be quite large 
        T* sendBuffer; // dont want our thing to get default constructed btw so we have to do some tricky things
};


template<triviallyDestructable T>
exchangeSimulator<T>::exchangeSimulator(int port, int batchSize)
         : port{port}, batchSize{batchSize}, allocator(),  msgs{std::make_unique<struct mmsghdr[]>(batchSize)}, iovecs{std::make_unique<struct iovec[]>(batchSize)}, sendBuffer{allocator.allocate(batchSize)} {
    
    for (int i{}; i < batchSize; ++i) {
        iovecs[i].iov_base = &sendBuffer[i];
        iovecs[i].iov_len = sizeof(T);
        msgs[i].msg_hdr.msg_iov = &iovecs[i];
        msgs[i].msg_hdr.msg_iovlen = 1;
    }

}

// concept that G must have void generator(T&)

template<triviallyDestructable T>
template<class G>
//requires isGenerator<G, T>
void exchangeSimulator<T>::run(std::atomic<bool>& terminateFlag, const struct sockaddr_in* dst, G& generator, int numSim){
        /*
       ssize_t sendto(int socket, const void *message, size_t length,
           int flags, const struct sockaddr *dest_addr,
           socklen_t dest_len);
    */

    cpu_set_t cpuset;
    CPU_ZERO(&cpuset);
    if(numSim==0) CPU_SET(globalConfigs::senderCore, &cpuset); // Bind to core 1(no hyperthreads)
    else CPU_SET(globalConfigs::senderCore2, &cpuset);
    
    pthread_t current_thread = pthread_self();
    pthread_setaffinity_np(current_thread, sizeof(cpu_set_t), &cpuset); // bind to core 7! Should not be interrupted, need this to be our "clock" of sorts
    
    // start old constructor(had to put this inside RUN because it modifies the network namespace of the thread so cannot be performed in the main thread)
    // generated by gemini start(slightly modified)
    int fd = open("/var/run/netns/sender_ns", O_RDONLY);
    if (fd == -1) {
        throw std::runtime_error("Failed to open namespace");
    }

    // 2. Switch THIS THREAD'S network namespace
    // CLONE_NEWNET ensures we only change the network namespace
    if (setns(fd, CLONE_NEWNET) == -1) {
        close(fd);
        throw std::runtime_error("Failed to switch namespace");
    }
    close(fd);
    // generated by gemini end
    // bascially this code is just loading the network namespace "sender_ns" from the netns folder and then binding this thread to that namespace to use its veth interface!

    // Creating socket file descriptor 
    if ( (sockfd = socket(AF_INET, SOCK_DGRAM, 0)) < 0 ) { 
        throw std::runtime_error("socket creation failed"); 
    } 

    memset(&addr, 0, sizeof(addr)); 

    // Filling server information 
    addr.sin_family    = AF_INET; // IPv4 
    addr.sin_addr.s_addr = htonl((10 << 24) + 2); // 10.0.0.2 ((10 << 24) + 2)
    addr.sin_port = htons(port); 

    // Bind the socket with the server address 
    if ( bind(sockfd, (const struct sockaddr *)&addr,  
            sizeof(addr)) < 0 ) 
    { 
        throw std::runtime_error("bind failed"); 
    } 

    /*int setsockopt(int sockfd, int level, int optname,
             const void *optval, socklen_t optlen);
*/
    if( setsockopt(sockfd, SOL_SOCKET, SO_BINDTODEVICE, "veth-tx", sizeof("veth-tx")) < 0){
        throw std::runtime_error("Could not bind to interface");
    }
    // end old constructor

    // connect syscall
   // have to reinterpret cast here because that is how c/linux does polymorphism without classes, top parts of class are still accessible after reinterpret case if shared
    connect(sockfd, reinterpret_cast<const sockaddr*>(dst), sizeof(*dst));
    int retval;
    while(!terminateFlag.load(std::memory_order_relaxed)){ // this is so fast that basically 100% of time is spend blocked by kernel doing I/O.
        // basically between in system, it appears that 300k is just fully on outgoing kernel I/O rather than the incoming processing!

        for(int i{}; i < batchSize; ++i){
            generator.generate(&sendBuffer[i]); // pass as reference, in-place construction of type T, do it this way because std::vector makes the object construct its self with .emplace()
        }        
        /*
               int sendmmsg(unsigned int n;
                    int sockfd, struct mmsghdr msgvec[n], unsigned int n,
                    int flags);

        */
        retval = sendmmsg(sockfd, msgs.get(), batchSize, 0);
        counter+=retval;
        //if (retval < 0){
        //    std::cout << retval << std::endl;
        //}
    }
}