#pragma once
#include <netinet/in.h> 
#include <sys/types.h>
#include <sys/socket.h>
#include <stdexcept>
#include <cstdlib> 
#include <arpa/inet.h> 
#include <netinet/in.h> 
#include <string.h>
#include <charconv>
#include <atomic>
#include <memory>
#include <pthread.h>
#include <sched.h>
#include <algorithm>
#include <sched.h>
#include <fcntl.h>
#include <unistd.h>
#include <iostream>
#include <liburing.h>
#include "systemVars.hpp"

template<class T>
concept triviallyDestructable = std::is_trivially_destructible_v<T> == true;

template <class Generator, class Generated>
concept isGenerator = requires(Generated a, Generator gen){
    {gen.generate(a)} -> std::same_as<void>;
};

template<triviallyDestructable T>
class exchangeSimulator {
    public:
        exchangeSimulator(int, int);

        template<class G>
        void run(std::atomic<bool>&, const struct sockaddr_in*, G& generator);

        int getCounter(){return counter;}
        void clearCounter(){counter = 0;}

    private:
        int sockfd;
        int port;
        int batchSize;
        int concurrent{5}; // sets how many send() minibatches should be going at any one point
        int counter{};
        struct sockaddr_in addr;
        std::unique_ptr<struct iovec[]> iovecs; // heap allocating all of this because batch size could be up to 1024 and these structs are >4 bytes so not lovely on stack T could be quite large 
        std::unique_ptr<T[]> sendBuffer; // dont want our thing to get default constructed btw so we have to do some tricky things
};


template<triviallyDestructable T>
exchangeSimulator<T>::exchangeSimulator(int port, int batchSize)
         : port{port}, batchSize{batchSize}, iovecs{std::make_unique<struct iovec[]>(batchSize*concurrent)}, sendBuffer{std::make_unique<T[]>(batchSize*concurrent)} {
    
    for (int i{}; i < batchSize*concurrent; ++i) {
        iovecs[i].iov_base = &sendBuffer[i]; // this always binds it to the right spot so we don't have to mess with iovec values from now on
        iovecs[i].iov_len = sizeof(sendBuffer[0]);
    }

}

template<triviallyDestructable T>
template<class G>
void exchangeSimulator<T>::run(std::atomic<bool>& terminateFlag, const struct sockaddr_in* dst, G& generator){

    cpu_set_t cpuset;
    CPU_ZERO(&cpuset);
    CPU_SET(systemVars::simulatorCore, &cpuset); // Bind to core 1(no hyperthreads)
    pthread_t current_thread = pthread_self();
    pthread_setaffinity_np(current_thread, sizeof(cpu_set_t), &cpuset); // bind to core 7! Should not be interrupted, need this to be our "clock" of sorts
    
    // start old constructor(had to put this inside RUN because it modifies the network namespace of the thread so cannot be performed in the main thread)
    // generated by gemini start(slightly modified)
    int fd = open("/var/run/netns/sender_ns", O_RDONLY | O_CLOEXEC);
    if (fd == -1) {
        throw std::runtime_error("Failed to open namespace");
    }

    // 2. Switch THIS THREAD'S network namespace
    // CLONE_NEWNET ensures we only change the network namespace
    if (setns(fd, CLONE_NEWNET) == -1) {
        close(fd);
        throw std::runtime_error("Failed to switch namespace");
    }
    close(fd);
    // generated by gemini end
    // bascially this code is just loading the network namespace "sender_ns" from the netns folder and then binding this thread to that namespace to use its veth interface!

    // Creating socket file descriptor 
    if ( (sockfd = socket(AF_INET, SOCK_DGRAM, 0)) < 0 ) { 
        throw std::runtime_error("socket creation failed"); 
    } 

    memset(&addr, 0, sizeof(addr)); 

    // Filling server information 
    addr.sin_family    = AF_INET; // IPv4 
    addr.sin_addr.s_addr = htonl((10 << 24) + 2); // 10.0.0.2 ((10 << 24) + 2)
    addr.sin_port = htons(port); 

    // Bind the socket with the server address 
    if ( bind(sockfd, (const struct sockaddr *)&addr,  
            sizeof(addr)) < 0 ) 
    { 
        throw std::runtime_error("bind failed"); 
    } 

    /*int setsockopt(int sockfd, int level, int optname,
             const void *optval, socklen_t optlen);
*/
    if( setsockopt(sockfd, SOL_SOCKET, SO_BINDTODEVICE, "veth-tx", sizeof("veth-tx")) < 0){
        throw std::runtime_error("Could not bind to interface");
    }
    // end old constructor
    // have to reinterpret cast here because that is how c/linux does polymorphism without classes, top parts of class are still accessible after reinterpret case if shared
    connect(sockfd, reinterpret_cast<const sockaddr*>(dst), sizeof(*dst));
    

    // setup io_uring for simulator, times two for a little bit of room just in case
    struct io_uring ring;
    io_uring_queue_init(batchSize*concurrent, &ring, IORING_FEAT_CQE_SKIP | IORING_SETUP_SQPOLL | IORING_SETUP_SUBMIT_ALL);
    struct io_uring_sqe *sqe{};
    struct io_uring_cqe *cqe{};
    // design for the simulator is just going to be adding a vectorized send and then looping on completion queue returns. Going to keep a count to ensure n message requests are always in SQ
    
    /*
       void io_uring_prep_send(struct io_uring_sqe *sqe,
                               int sockfd,
                               const void *buf,
                               size_t len,
                               int flags);
    */
    // IORING_SEND_VECTORIZED, we don't want to do zero-copy because we legit are < 1 cache line so one op :D
    // need IOSQE_BUFFER_SELECT to serialize but this is just the sim so I don't care about correctness here.(Worse Is Better)
    //io_uring_prep_send(sqe, sockfd, &iovecs, batchSize, IORING_SEND_VECTORIZED)
    // basically we have a bunch of vectorized calls, each of size bufferSize/concurrent = batchSize
    // we maintain track of how many concurrent by incrementing on SQ and decrementing on CQ.
    // this means we never slow down the kernel/

    // structure will be filling the send buffer on start and then polling the completion queue
    // when we get back our index from the user_data field, we can reset that message batch and send another vectorized call to keep concurrent sends at needed value!


    // build initial messages
    for(int i{}; i < batchSize*concurrent; ++i){
        generator.generate(&sendBuffer[i]); 
    }    

    // fill up queue on init!
    for (std::int64_t i{}; i < concurrent; ++i){
        sqe = io_uring_get_sqe(&ring);
        io_uring_prep_send(sqe, sockfd, &iovecs[batchSize*i], batchSize, IORING_SEND_VECTORIZED);
        io_uring_sqe_set_data64(sqe, i);
        io_uring_submit(&ring);
    }

    int retval{};
    int replacingIndex{};
    while(!terminateFlag.load(std::memory_order_relaxed)){

        // poll completion queue and re-build and re-send as completions come in!
        retval = io_uring_wait_cqe(&ring, &cqe);
        if (retval < 0){
            continue;
        }
        replacingIndex = cqe->user_data;
        io_uring_cqe_seen(&ring, cqe);

        if (cqe->res > 0){
            counter += cqe->res;
        } else{
            std::cout << cqe->res << std::endl;
        }
        
        // generate new data for batch
        for(int i{}; i < batchSize; ++i){
            generator.generate(&sendBuffer[i+replacingIndex*batchSize]);
        }
        // send message
        sqe = io_uring_get_sqe(&ring);
        io_uring_prep_send(sqe, sockfd, &iovecs[batchSize*replacingIndex], batchSize, IORING_SEND_VECTORIZED);
        io_uring_sqe_set_data64(sqe, replacingIndex);
        io_uring_submit(&ring);
    }
}