#pragma once
#include <memory>
#include <cstdlib>
#include <cstring>
#include <algorithm>
#include <liburing.h>
#include <sys/types.h>
#include <arpa/inet.h> 
#include <stdexcept>
#include <cstring>
#include <sys/socket.h>
#include "systemVars.hpp"


namespace MSG_GLOBALS {
    constexpr int MSG_BATCH_SIZE = 128; // for the producer
    constexpr int MSG_MAX_SIZE = 48;//193; // max size of an OUCH message with all flags is 193 bytes
    constexpr double TIMEOUT = 100000; // 1ms timeout
}

// type message must have empty() function which checks if it is there or not
// also implement setEmpty()

template <class Message>
class uringConsumer {
    private:
        int sockfd;
        int port;
        int bufferSize;
        int consumerIndex{}; // we always start producing before consuming so its fine... usually
        struct io_uring ring;
        struct iovec iovecs[MSG_GLOBALS::MSG_BATCH_SIZE];
        struct msghdr msgs[MSG_GLOBALS::MSG_BATCH_SIZE];
        struct timespec timeout;
        struct sockaddr_in addr;
        std::unique_ptr<Message[]> buffer{};

    public:
        uringConsumer(int bufferSize, int port); 

        template <class Consumer>
        void PollSocket(std::atomic<bool>& terminateFlag, Consumer& accumulator);

        void clear(){
            consumerIndex = 0;
            std::memset(buffer.get(), 0, bufferSize*sizeof(buffer[0]));
        }

        struct sockaddr_in* getAddr(){return &addr;}
};

template <class Message>
uringConsumer<Message>::uringConsumer(int bufferSize, int port) : port{port}, bufferSize{bufferSize}, buffer{std::make_unique_for_overwrite<Message[]>(bufferSize)}{
    // do iovecs setup
    // generated by gemini start(slightly modified)
    int fd = open("/var/run/netns/receiver_ns", O_RDONLY | O_CLOEXEC);
    if (fd == -1) {
        throw std::runtime_error("Failed to open namespace");
    }

    // 2. Switch THIS THREAD'S network namespace
    // CLONE_NEWNET ensures we only change the network namespace
    if (setns(fd, CLONE_NEWNET) == -1) {
        close(fd);
        throw std::runtime_error("Failed to switch namespace");
    }
    close(fd);
    // generated by gemini end

    // Creating socket file descriptor 
    if ( (sockfd = socket(AF_INET, SOCK_DGRAM, 0)) < 0 ) { 
        throw std::runtime_error("socket creation failed"); 
    } 

    memset(&addr, 0, sizeof(addr)); 
    
    // Filling server information 
    addr.sin_family    = AF_INET; // IPv4 
    addr.sin_addr.s_addr = htonl((10 << 24) + 1);//htonl((10 << 24) + 1); // 10.0.0.1 ((10 << 24) + 2); 
    addr.sin_port = htons(port); 

    // Bind the socket with the server address 
    if ( bind(sockfd, (const struct sockaddr *)&addr,  
            sizeof(addr)) < 0 ) 
    { 
        throw std::runtime_error("bind failed"); 
    }
    
    if (setsockopt(sockfd, SOL_SOCKET, SO_BINDTODEVICE, "veth-rx", sizeof("veth-rx")) < 0){
        throw std::runtime_error("Producer could not bind to network interface");
    }

    timeout.tv_sec = 0;
    timeout.tv_nsec = MSG_GLOBALS::TIMEOUT;

    // zero these
    std::memset(iovecs, 0, sizeof(iovec));
    std::memset(msgs, 0, sizeof(mmsghdr));

    // initalize message array. We need to have an array of bufferSize holding the corresponding recvmsg information for corresponding buffer spot.
    // because this in async, we should just hold all the messages static so we can always point to the msghdr and never have to construct! 
    for (int i{0}; i < bufferSize; ++i) {
        iovecs[i].iov_base = &buffer[i]; // done later now, unneccesary to do this because overridden later
        iovecs[i].iov_len = MSG_GLOBALS::MSG_MAX_SIZE;
        msgs[i].msg_iov = &iovecs[i];
        msgs[i].msg_iovlen = 1;
    }


    /// setup kernel io_uring
    io_uring_queue_init(MSG_GLOBALS::MSG_BATCH_SIZE, &ring, IORING_FEAT_CQE_SKIP | IORING_SETUP_SQPOLL | IORING_SETUP_SUBMIT_ALL);
    //IORING_SETUP_SQPOLL
    // IORING_FEAT_CQE_SKIP
    // IORING_SETUP_SUBMIT_ALL could be userful
}


template <class Message>
template <class Consumer>
void uringConsumer<Message>::PollSocket(std::atomic<bool>& terminateFlag, Consumer& accumulator){
    
    cpu_set_t cpuset;
    CPU_ZERO(&cpuset);
    CPU_SET(systemVars::consumerCore, &cpuset); // Bind to core 3, not hyperthreaded with producer or sim
    pthread_t current_thread = pthread_self();
    pthread_setaffinity_np(current_thread, sizeof(cpu_set_t), &cpuset); 

    // enter all of buffer into sqe
    struct io_uring_sqe *sqe{};
    for (int i{}; i < bufferSize; ++i){
        sqe = io_uring_get_sqe(&ring);
        io_uring_prep_recvmsg(sqe, sockfd, &msgs[consumerIndex], IOSQE_CQE_SKIP_SUCCESS);
    }

    while(!terminateFlag.load(std::memory_order_relaxed)){ 

        if (!buffer[consumerIndex].empty()){ // if we have data, consume it 
            // we should ensure that we have another place in the submission queue before consuming. If not, left in weird spot.
            sqe = io_uring_get_sqe(&ring);
            if (sqe == nullptr){ // just busywaits on the SQE
                continue;
            }

            // here we consume the data and ask for more in this specfic index of the buffer
            accumulator.consume(buffer[consumerIndex]); // because the message is just a pointer to the aligned raw bytes in the buffer, pass by reference!
            buffer[consumerIndex].setEmpty(); // ensure we don't later read this as having data
            io_uring_prep_recvmsg(sqe, sockfd, &msgs[consumerIndex], IOSQE_CQE_SKIP_SUCCESS);
            io_uring_submit(&ring);
            consumerIndex = (consumerIndex + 1) % bufferSize;
        }
    }
    io_uring_queue_exit(&ring); // cleanup
}