#include <sys/types.h>
#include <arpa/inet.h> 
#include <stdexcept>
#include <cstring>
#include <sys/socket.h>
#include "Producer.hpp"
#include "SPSC.hpp"
#include <sched.h>
#include <time.h>
#include <fcntl.h>
#include <unistd.h>
#include <iostream>

Producer::Producer (int port, int bufferSize)
                         : port{port}, bufferSize{bufferSize} {
            

    // generated by gemini start(slightly modified)
    int fd = open("/var/run/netns/receiver_ns", O_RDONLY | O_CLOEXEC);
    if (fd == -1) {
        throw std::runtime_error("Failed to open namespace");
    }

    // 2. Switch THIS THREAD'S network namespace
    // CLONE_NEWNET ensures we only change the network namespace
    if (setns(fd, CLONE_NEWNET) == -1) {
        close(fd);
        throw std::runtime_error("Failed to switch namespace");
    }
    close(fd);
    // generated by gemini end

    // Creating socket file descriptor 
    if ( (sockfd = socket(AF_INET, SOCK_DGRAM, 0)) < 0 ) { 
        throw std::runtime_error("socket creation failed"); 
    } 

    memset(&addr, 0, sizeof(addr)); 
    
    // Filling server information 
    addr.sin_family    = AF_INET; // IPv4 
    addr.sin_addr.s_addr = htonl((10 << 24) + 1);//htonl((10 << 24) + 1); // 10.0.0.1 ((10 << 24) + 2); 
    addr.sin_port = htons(port); 

    // Bind the socket with the server address 
    if ( bind(sockfd, (const struct sockaddr *)&addr,  
            sizeof(addr)) < 0 ) 
    { 
        throw std::runtime_error("bind failed"); 
    }

    if (setsockopt(sockfd, SOL_SOCKET, SO_BINDTODEVICE, "veth-rx", sizeof("veth-rx")) < 0){
        throw std::runtime_error("Producer could not bind to network interface");
    }

    timeout.tv_sec = 0;
    timeout.tv_nsec = MSG_GLOBALS::TIMEOUT;

    // zero these
    std::memset(iovecs, 0, sizeof(iovec)*MSG_GLOBALS::MSG_BATCH_SIZE);
    std::memset(msgs, 0, sizeof(mmsghdr)*MSG_GLOBALS::MSG_BATCH_SIZE);

    // initalize msg
    for (size_t i{0}; i < MSG_GLOBALS::MSG_BATCH_SIZE; ++i) {
        //iovecs[i].iov_base = q.buffer[i].message; // done later now, unneccesary to do this because overridden later
        iovecs[i].iov_len = MSG_GLOBALS::MSG_MAX_SIZE;
        msgs[i].msg_hdr.msg_iov = &iovecs[i];
        msgs[i].msg_hdr.msg_iovlen = 1;
    }
}