#include <sys/types.h>
#include <arpa/inet.h> 
#include <stdexcept>
#include <cstring>
#include <sys/socket.h>
#include "Producer.hpp"
#include "SPSC.hpp"
#include <sched.h>
#include <fcntl.h>
#include <unistd.h>
#include <iostream>

// how are we doing this batched SPSC?
// we add to ring buffer in batches to minimize kernel mode switch overhead, fill in min(batch size, space left) chunks!

// we dont want somethign to read while we write so lets set a "read boundary" and then we write
// dont want to overwrite while we read(could happen with looping around) so need "write boundary"

// do this with atomics basically, don't actually need locks since only one thread is writing each, only need fences to make sure we release memory when its okay to

// so basically, we check lock status of things to find the boundary and then fill in up to that!
// we have two atomics then: the tail and the head


// structure: should probably have a "SPSC queue" class which owns the buffer, producer and consumer should not own the buffer
// that structure makes the atomics and owns

Producer::Producer (int port, int bufferSize)
                         : port{port}, bufferSize{bufferSize} {
            

    // generated by gemini start(slightly modified)
    int fd = open("/var/run/netns/receiver_ns", O_RDONLY | O_CLOEXEC);
    if (fd == -1) {
        throw std::runtime_error("Failed to open namespace");
    }

    // 2. Switch THIS THREAD'S network namespace
    // CLONE_NEWNET ensures we only change the network namespace
    if (setns(fd, CLONE_NEWNET) == -1) {
        close(fd);
        throw std::runtime_error("Failed to switch namespace");
    }
    close(fd);
    // generated by gemini end

    // Creating socket file descriptor 
    if ( (sockfd = socket(AF_INET, SOCK_DGRAM, 0)) < 0 ) { 
        throw std::runtime_error("socket creation failed"); 
    } 

    memset(&addr, 0, sizeof(addr)); 
    
    // Filling server information 
    addr.sin_family    = AF_INET; // IPv4 
    addr.sin_addr.s_addr = htonl((10 << 24) + 1);//htonl((10 << 24) + 1); // 10.0.0.1 ((10 << 24) + 2); 
    addr.sin_port = htons(port); 

    // Bind the socket with the server address 
    if ( bind(sockfd, (const struct sockaddr *)&addr,  
            sizeof(addr)) < 0 ) 
    { 
        throw std::runtime_error("bind failed"); 
    }
    
    if (setsockopt(sockfd, SOL_SOCKET, SO_BINDTODEVICE, "veth-rx", sizeof("veth-rx")) < 0){
        throw std::runtime_error("Producer could not bind to network interface");
    }

    timeout.tv_sec = 0;
    timeout.tv_nsec = MSG_GLOBALS::TIMEOUT;

    // zero these
    std::memset(iovecs, 0, sizeof(iovec)*MSG_GLOBALS::MSG_BATCH_SIZE);
    std::memset(msgs, 0, sizeof(mmsghdr)*MSG_GLOBALS::MSG_BATCH_SIZE);

    // initalize msg
    for (size_t i{0}; i < MSG_GLOBALS::MSG_BATCH_SIZE; ++i) {
        //iovecs[i].iov_base = q.buffer[i].message; // done later now, unneccesary to do this because overridden later
        iovecs[i].iov_len = MSG_GLOBALS::MSG_MAX_SIZE;
        msgs[i].msg_hdr.msg_iov = &iovecs[i];
        msgs[i].msg_hdr.msg_iovlen = 1;
    }
}